#!/usr/bin/env bash
# Residual-policy comparison launcher.
#
# Quick start:
#   OPENPI_CHECKPOINT_ROOT=/path/to/checkpoints \
#   OPENPI_BASE_INIT_CHECKPOINT=/path/to/checkpoints/30000/params \
#   OPENPI_LOCAL_LEROBOT_DATA_ROOT=/path/to/online/episodes \
#   bash scripts/train_online_dagger_lerobot_residual.sh
#
# The base policy is frozen while the residual head is trained. Set
# OPENPI_RESIDUAL_INIT_CHECKPOINT to resume residual weights independently.
# Set OPENPI_DRY_RUN=1 to print the command without starting training.
#
# Shared path, GPU, logging, and run-mode overrides are described in
# train_online_dagger_lerobot_reactive.sh. Residual data differs from LIFT:
# control_flag is required, but the default intervention value is -1 rather
# than 1 (Pi0Config.residual_intervention_value). Do not relabel the source
# silently; select the value matching your recording convention in the config.
# Offline residual targets are zero. New online targets are generated by the
# frozen base at intervention timesteps and retained in memory for this run;
# no offline rollout or persistent residual-target sidecar cache is built.
# OPENPI_RESIDUAL_TARGET_NUM_STEPS and OPENPI_RESIDUAL_TARGET_BATCH_SIZE control
# this target-generation pass. See src/openpi/training/residual_target_cache.py.
#
# OPENPI_BASE_INIT_CHECKPOINT always supplies the frozen base policy.
# OPENPI_RESIDUAL_INIT_CHECKPOINT optionally overlays a previously trained head;
# this starts a new optimizer run, unlike OPENPI_RESUME=1, which restores the
# existing training state. For serving a residual-only checkpoint, also set
# the selected config's weight_loader to the same base checkpoint.
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "${script_dir}/.." && pwd)"
cd "${repo_root}"

python_bin="${OPENPI_PYTHON:-${repo_root}/.venv/bin/python}"
if [[ ! -x "${python_bin}" ]]; then
    echo "Python executable not found or not executable: ${python_bin}" >&2
    exit 1
fi

# Paths and runtime defaults. Override any of these with environment variables.
export HF_LEROBOT_HOME="${HF_LEROBOT_HOME:-${HOME}/.cache/huggingface/lerobot}"
export OPENPI_CHECKPOINT_ROOT="${OPENPI_CHECKPOINT_ROOT:-${repo_root}/checkpoints}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export XLA_PYTHON_CLIENT_PREALLOCATE="${XLA_PYTHON_CLIENT_PREALLOCATE:-false}"
export XLA_PYTHON_CLIENT_MEM_FRACTION="${XLA_PYTHON_CLIENT_MEM_FRACTION:-0.95}"
export OPENPI_JAX_DEBUG="${OPENPI_JAX_DEBUG:-0}"
export OPENPI_JAX_DEBUG_BREAK="${OPENPI_JAX_DEBUG_BREAK:-0}"
export OPENPI_JAX_DEBUG_TAGS="${OPENPI_JAX_DEBUG_TAGS:-residual/targets,residual/prediction,train/metrics}"
export JAX_DEBUG_NANS="${JAX_DEBUG_NANS:-0}"

# Experiment identity and base/residual checkpoint initialization.
config_name="${OPENPI_CONFIG_NAME:-pi05_iPhoneSingle_book_insertion_v3_100_residual}"
exp_name="${OPENPI_EXP_NAME:-${config_name#pi05_iPhoneSingle_}_online_$(date -u +%Y%m%d_%H%M%S)}"
checkpoint_root="${OPENPI_CHECKPOINT_ROOT}"
base_init_checkpoint="${OPENPI_BASE_INIT_CHECKPOINT:-${checkpoint_root}/30000/params}"
residual_init_checkpoint="${OPENPI_RESIDUAL_INIT_CHECKPOINT:-}"
gpu_ids="${OPENPI_CUDA_VISIBLE_DEVICES-${CUDA_VISIBLE_DEVICES-0,1}}"

# Online data source. A local root should contain LeRobot episode directories.
local_data_root="${OPENPI_LOCAL_LEROBOT_DATA_ROOT:-}"
online_repo_id="${OPENPI_ONLINE_REPO_ID:-flexiv/${config_name#pi05_iPhoneSingle_}_online_$(date -u +%Y%m%d_%H%M%S)}"
datacloud_endpoint="${OPENPI_DATACLOUD_ENDPOINT:-}"
identifier="${OPENPI_IDENTIFIER:-}"
fetch_interval="${OPENPI_FETCH_INTERVAL:-1}"
robot_type="${OPENPI_ROBOT_TYPE:-single_iphone_flexiv}"
fps="${OPENPI_FPS:-10}"
task_description="${OPENPI_TASK_DESCRIPTION:-}"

# Training, fetching, and residual-target cache controls.
save_interval="${OPENPI_SAVE_INTERVAL:-1000}"
log_interval="${OPENPI_LOG_INTERVAL:-5}"
prefetch_batches="${OPENPI_PREFETCH_BATCHES:-2}"
sampler_update_interval="${OPENPI_SAMPLER_UPDATE_INTERVAL:-10}"
residual_target_num_steps="${OPENPI_RESIDUAL_TARGET_NUM_STEPS:-10}"
residual_target_batch_size="${OPENPI_RESIDUAL_TARGET_BATCH_SIZE:-}"
num_train_steps="${OPENPI_NUM_TRAIN_STEPS:-}"
batch_size="${OPENPI_BATCH_SIZE:-}"
min_online_ratio="${OPENPI_MIN_ONLINE_RATIO:-0.5}"
max_online_ratio="${OPENPI_MAX_ONLINE_RATIO:-0.5}"
initial_online_weight="${OPENPI_INITIAL_ONLINE_WEIGHT:-0.5}"

# New runs are timestamped; existing output is never overwritten by default.
# Set OPENPI_EXP_NAME with OPENPI_RESUME=1 or OPENPI_OVERWRITE=1 deliberately.
run_mode_args=()
if [[ "${OPENPI_RESUME:-0}" == "1" ]]; then
    run_mode_args=(--resume)
elif [[ "${OPENPI_OVERWRITE:-0}" == "1" ]]; then
    run_mode_args=(--overwrite)
fi
if [[ "${OPENPI_RESUME:-0}" == "1" && "${OPENPI_OVERWRITE:-0}" == "1" ]]; then
    echo "OPENPI_RESUME and OPENPI_OVERWRITE cannot both be 1." >&2
    exit 1
fi

# Only add optional CLI flags when explicitly requested.
optional_args=()
if [[ -n "${OPENPI_FSDP_DEVICES:-}" ]]; then
    optional_args+=(--fsdp-devices "${OPENPI_FSDP_DEVICES}")
fi
if [[ "${OPENPI_ALLOW_OFFLINE_WARM_START:-1}" == "0" ]]; then
    optional_args+=(--no-allow-offline-warm-start)
fi
if [[ -n "${num_train_steps}" ]]; then
    optional_args+=(--num-train-steps "${num_train_steps}")
fi
if [[ -n "${batch_size}" ]]; then
    optional_args+=(--batch-size "${batch_size}")
fi
if [[ -n "${residual_target_batch_size}" ]]; then
    optional_args+=(--residual-target-batch-size "${residual_target_batch_size}")
fi

init_args=(--base-init-checkpoint "${base_init_checkpoint}")
if [[ -n "${residual_init_checkpoint}" ]]; then
    init_args+=(--residual-init-checkpoint "${residual_init_checkpoint}")
fi

if [[ ! -d "${base_init_checkpoint}" ]]; then
    echo "Base checkpoint params directory not found: ${base_init_checkpoint}" >&2
    echo "Set OPENPI_BASE_INIT_CHECKPOINT or OPENPI_CHECKPOINT_ROOT." >&2
    exit 1
fi
if [[ -n "${residual_init_checkpoint}" && ! -d "${residual_init_checkpoint}" ]]; then
    echo "Residual checkpoint params directory not found: ${residual_init_checkpoint}" >&2
    exit 1
fi

# Keep the command in an array so paths and task text remain shell-safe.
command=(
    env CUDA_VISIBLE_DEVICES="${gpu_ids}"
    "${python_bin}" "${repo_root}/scripts/train_online_dagger.py"
    --config-name "${config_name}"
    --exp-name "${exp_name}"
    --checkpoint-base-dir "${checkpoint_root}"
    "${init_args[@]}"
    "${run_mode_args[@]}"
    "${optional_args[@]}"
    --datacloud-endpoint "${datacloud_endpoint}"
    --identifier "${identifier}"
    --local-lerobot-data-root "${local_data_root}"
    --online-repo-id "${online_repo_id}"
    --fetch-interval "${fetch_interval}"
    --robot-type "${robot_type}"
    --fps "${fps}"
    --task-description "${task_description}"
    --online-use-wrench
    --save-interval "${save_interval}"
    --log-interval "${log_interval}"
    --prefetch-batches "${prefetch_batches}"
    --sampler-update-interval "${sampler_update_interval}"
    --residual-target-num-steps "${residual_target_num_steps}"
    --min-online-ratio "${min_online_ratio}"
    --max-online-ratio "${max_online_ratio}"
    --initial-online-weight "${initial_online_weight}"
    "$@"
)

if [[ "${OPENPI_DRY_RUN:-0}" == "1" ]]; then
    printf 'Would run:'
    printf ' %q' "${command[@]}"
    printf '\n'
    exit 0
fi

exec "${command[@]}"
